// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/register": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/login" | "/register";
  };
  "./pages/SignIn.tsx": {
    id: "pages/SignIn";
    page: "/login";
  };
  "./pages/SignUp.tsx": {
    id: "pages/SignUp";
    page: "/register";
  };
  "App.tsx": {
    id: "App";
    page: "/";
  };
};